# Generated by Django 2.2 on 2020-05-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20200518_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='direction',
            field=models.TextField(blank=True),
        ),
    ]
